# Generated by Django 4.2.4 on 2023-09-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='lname',
            new_name='last_name',
        ),
    ]
